name: Terraform CI/CD

on:
 push:
    branches:
      - main

jobs:
 plan-apply:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Init & Plan
        run: |
          terraform init -input=false
          terraform plan

 apply:
    needs: plan-apply
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Apply
        run: terraform apply -auto-approve

 plan-destroy:
    needs: apply
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Plan Destroy
        run: terraform plan -destroy

 destroy:
    needs: plan-destroy
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Destroy
        run: terraform apply -auto-approve
